### ISSUE TITLE
Missing Settings for additional Applications

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/IntuneDocs.de-de#37]
We're trying to configure Edge as a replacement for Managed Browser and currently there is as far as i've seen no documentation about MAM settings we can set for edge.
Are there no settings or is it just missing from the documentation?

BG Christoph

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fcd2634b-7fa3-bff9-c2bf-dfd5b5dac21d
* Version Independent ID: 405802e7-bcf7-3767-b6e1-3ebd12e1bebd
* Content: [Verwalten des Webzugriffs mit der Managed Browser-App](https://docs.microsoft.com/de-de/intune/app-configuration-managed-browser)
* Content Source: [intune/app-configuration-managed-browser.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune/app-configuration-managed-browser.md)
* Service: **microsoft-intune**
* Product: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/IntuneDocs #1383](https://github.com/MicrosoftDocs/IntuneDocs/issues/1383) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @chwilfing, 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/1383. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
