### ISSUE TITLE
Fehlerbehebung funktioniert nicht

### ISSUE THREAD

**Issue by jasc76** [MicrosoftDocs/IntuneDocs.de-de#40]
Auch nach löschen des Geschäftsmailkontos zeigt er weiterhin an es wäre ein Konto vorhanden
DAS STIMMT ABER NICHT
App und Hilfeseite fehlerhaft

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bf9f3f90-c272-97cc-cc4e-367628358303
* Version Independent ID: 29e86a5c-cdd4-a4e6-8af1-2571b1faa96b
* Content: [Es wurde ein vorhandenes geschäftliches E-Mail-Konto gefunden](https://docs.microsoft.com/de-de/intune-user-help/existing-company-email-account-found#feedback)
* Content Source: [intune-user-help/existing-company-email-account-found.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune-user-help/existing-company-email-account-found.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @jasc76, thanks for taking the time to provide feedback about Intune Company Portal. I recommend that you provide this info through our Feedback channel, so that you can get support for the deleted email account. See the [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas). I'm closing this issue as there's nothing actionable for docs at this time.
