### ISSUE TITLE
App Information require Appstore URL

### ISSUE THREAD

**Issue by jhueppauff** [MicrosoftDocs/IntuneDocs.de-de#43]
Within the "Win32" - "App Information" Dialog there is a Field which seems not to be covered in the documentation.
Field Name: "Appstore URL".
As this Field is mandatory it cant be skipped.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 131c1925-c9df-2ce2-43bb-db329954461b
* Version Independent ID: d527f760-a258-7367-a63d-ac0e409c8450
* Content: [Hinzufügen von Win32-Apps zu Microsoft Intune](https://docs.microsoft.com/de-de/intune/apps-win32-app-management)
* Content Source: [intune/apps-win32-app-management.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by jhueppauff** [comment]
![grafik](https://user-images.githubusercontent.com/20532954/56510848-52e13200-652b-11e9-9e31-25089f843d26.png)

**Comment by CeciAc** [comment]
Hello, @jhueppauff

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/2316

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
