### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/IntuneDocs.de-de#44]
Hi, is there an Entity Relationship Diagram to this page? It would be quite helpful to understand the relations between tables. Thanks

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f6db025d-0d22-ed38-a5c6-5e971959e5e7
* Version Independent ID: 6b74daaa-e71e-8587-4c9c-c006ad6b89ce
* Content: [Sammlungen von Intune Date Warehouse - Microsoft Intune](https://docs.microsoft.com/de-de/intune/intune-data-warehouse-collections#mamdevicehealths)
* Content Source: [intune/intune-data-warehouse-collections.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune/intune-data-warehouse-collections.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by CeciAc** [comment]
Hello, @AlexSchwerzmann

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/2437

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
